### PR TITLE
Update usage.md

### PR DESCRIPTION
**Pull request by bryangruneberg**
A few tweaks to improve the English in the (already great!) documentation

### CODE REVIEW

**Comment by bryangruneberg** [comment]
@nunomaduro - I hope these small tweaks to the English in the documentation help the project! Let me know if you'd like me to change any of my proposed tweaks. I'm happy for feedback :) 👋

**Comment by nunomaduro** [comment]
Seems good to me! Great contribution! Thanks a lot! 👏

**Comment by bryangruneberg** [comment]
Thanks for your work on this - I'm writing up my first CLI commands and its an absolute pleasure working with your stuff @nunomaduro !

**Comment by nunomaduro** [comment]
@bryangruneberg That's great! Let me know if you need help!

**Pull request merged**
