### PR TITLE
Updated dependencies and little style refresh

### PR DESCRIPTION
**Pull request by billmn**
I have updated project dependencies to Tailwind to 1.9, added Tailwind Typography and made a little style refresh. Also fixes responsive for smartphone and tablets. 

Let me know what you think 👋

localhost_3000_

localhost_3000_docs_exception-handler_

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thank you!

**Comment by nunomaduro** [comment]
@billmn Are you interested in being added as maintainer of this project? You would have green card for this kind of improvements. cc @owenvoke

**Comment by owenvoke** [comment]
Thank you for this @billmn, brilliant work. :+1:

**Comment by billmn** [comment]
> @billmn Are you interested in being added as maintainer of this project? You would have green card for this kind of improvements. cc @owenvoke

Sure, it would be a pleasure!

Thank you for your proposal @nunomaduro

**Pull request merged**
