### PR TITLE
Fix wrong heading level for title

### PR DESCRIPTION
**Pull request by godbout**
Just making it consistent with all the other pages. Apologies if this is wrong and I'm missing something!

### CODE REVIEW

**Comment by nunomaduro** [comment]
Thanks! It's perfect. Don't hesitate to do more commits like that.

**Comment by godbout** [comment]
`Do hesitate` 😅️

**Comment by nunomaduro** [comment]
@godbout Fixed 👍

**Comment by godbout** [comment]
Was just teasing. Obrigado!

**Pull request merged**
